[package]
name = "os_funtimes"
version = "0.1.0"
authors = ["Theodore DeRego <tderego94@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
spin = "0.3.4"
multiboot2 = { git = "https://github.com/phil-opp/multiboot2-elf64" }
